
ansible_user: david
ansible_ssh_private_key_file: ~/.ssh/id_rsa
ansible_python_interpreter: /usr/bin/python3

system_packages:
  - sudo
  - exfat-fuse
  - exfatprogs
  - curl
  - systemd-resolved
  - samba
  - zip
  - unzip

system_mounts:
  - src: "LABEL=External2TB"
    path: "/mnt/bmo2"

pip_install_packages:
  - name: docker

portainer_server_ip: bmo.cassowary-harmonic.ts.net
portainer_api_url: "http://{{ portainer_server_ip }}:9000"
portainer_admin_user: admin
portainer_endpoint_id: "3"

tailscale_tags: ["server"]

caddy_hostname: bmo
caddy_domain: cassowary-harmonic.ts.net

immich_upload_location: /mnt/bmo2/PHOTOS/immich_uploads
immich_db_data_location: ./postgres
immich_version: v2
immich_db_username: postgres
immich_db_database_name: immich